"""empty message

Revision ID: 12f65dd815ea
Revises: fd1b1d507d53
Create Date: 2024-10-21 17:28:44.350127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f65dd815ea'
down_revision: Union[str, None] = 'fd1b1d507d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
