"""empty message

Revision ID: 5c5cbf0f96c1
Revises: 505131f37eb3
Create Date: 2024-10-20 21:50:20.079833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5cbf0f96c1'
down_revision: Union[str, None] = '505131f37eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_tg_username'), 'users', ['tg_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_username'), table_name='users')
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
