"""empty message

Revision ID: a4b21a1859e0
Revises: 5ece991f5374
Create Date: 2024-10-17 21:37:02.955620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b21a1859e0'
down_revision: Union[str, None] = '5ece991f5374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_recipient_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_recipient_id_fkey', 'messages', 'users', ['recipient_id'], ['id'])
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
