"""empty message

Revision ID: b8641e330fb3
Revises: a4b21a1859e0
Create Date: 2024-10-19 20:55:35.328106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8641e330fb3'
down_revision: Union[str, None] = 'a4b21a1859e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_tg_username'), 'users', ['tg_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_username'), table_name='users')
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
