"""empty message

Revision ID: dfbaf7715782
Revises: b8641e330fb3
Create Date: 2024-10-20 13:51:57.972738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbaf7715782'
down_revision: Union[str, None] = 'b8641e330fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed_to_bot', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_subscribed_to_bot')
    # ### end Alembic commands ###
