"""empty message

Revision ID: fd1b1d507d53
Revises: 60cabdd0da26
Create Date: 2024-10-21 16:52:21.576850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1b1d507d53'
down_revision: Union[str, None] = '60cabdd0da26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_auth_token', table_name='users')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_auth_token', 'users', ['auth_token'], unique=True)
    # ### end Alembic commands ###
